version: '3.8'

services:
  backend:
    build: ./backend
    container_name: aletheia_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - mongo

  user-ui:
    build: ./frontend/user-ui
    container_name: aletheia_user_ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/user-ui:/app
    env_file:
      - .env
    stdin_open: true
    tty: true

  legal-ui:
    build: ./frontend/legal-ui
    container_name: aletheia_legal_ui
    ports:
      - "3001:3000"  # El puerto interno de Vite es 3000 por defecto
    volumes:
      - ./frontend/legal-ui:/app
    env_file:
      - .env
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: aletheia_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo_data:
