services:
  backend:
    build: ./backend
    container_name: aletheia_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - mongo

  user-ui:
    build: ./frontend/user-ui
    container_name: aletheia_user_ui
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true

  legal-ui:
    build: ./frontend/legal-ui
    container_name: aletheia_legal_ui
    ports:
      - "3001:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: aletheia_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: aletheia_keycloak
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=dev-file
    volumes:
      - ./keycloak/realm-config:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    depends_on:
      - mongo


volumes:
  mongo_data:
